VSF2-279 - Added tests for adding products to cart
BitBagCommerce/SyliusVueStorefront2Frontend pull request #198
Opened 2023-07-18 12:12 UTC by DawidFrankiewicz

Test checks:
- Adding product to cart
- Adding product to cart with changed quantity
- Adding product to cart with changed variant option

2023-07-18 13:28 UTC, dead-playmod requested changes

2023-07-18 13:28 UTC, dead-playmod commented on packages/theme/tests/e2e/fixtures/api/e2e-api-responses-modifications.ts
> +    for (const selectedVariant of selectedVariants) {
Is there any reason for going through variants in a loop if at the end you will only push on into the cart?

2023-07-18 13:28 UTC, dead-playmod commented on packages/theme/tests/e2e/fixtures/api/e2e-api-responses-modifications.ts
> +    return this;
What does `this` mean in this context, did you mean to return it?

2023-07-18 13:28 UTC, dead-playmod commented on packages/theme/tests/e2e/fixtures/api/e2e-api-responses-modifications.ts
> +  setProductVariant(variantType, variantId) {
Is this function nesesery, I can't see it being used anywhere?

2023-07-18 13:28 UTC, dead-playmod commented on packages/theme/tests/e2e/pages/category.ts
> +  public addProductToCart(
Maybe try moving this function to `productModal`, because same operation can be made on any other page with product modal.

2023-07-19 04:29 UTC, DawidFrankiewicz commented on packages/theme/tests/e2e/fixtures/api/e2e-api-responses-modifications.ts
> +    for (const selectedVariant of selectedVariants) {
Products can have many variants to select like size and color, that is why it loops over an array here, many options can be changed

2023-07-19 04:41 UTC, DawidFrankiewicz commented on packages/theme/tests/e2e/pages/category.ts
> +  public addProductToCart(
This function is specific for category page, because it start on category page, opens modal and adds product. It will probably be slightly different for products in search.

2023-07-19 08:05 UTC, dead-playmod commented on packages/theme/tests/e2e/pages/category.ts
> +  public addProductToCart(
I think you could still take the part with selecting variant and quantity and make a helper function in modal it self part with pressing button to toggle modal can be left here.

2023-07-19 08:08 UTC, DawidFrankiewicz commented on packages/theme/tests/e2e/pages/category.ts
> +  public addProductToCart(
This change is already made for other test, it will be added soon.

2023-07-19 08:11 UTC, merged