VSF2-141 - Added seperate query for useFacet()
BitBagCommerce/SyliusVueStorefront2Frontend pull request #63
Opened 2023-04-06 12:07 UTC by DawidFrankiewicz

## Description
Added seperate query for useFacet(), it fetches less data than general use query used before.

Changed description to short description in list view on category page.

2023-04-24 11:31 UTC, dead-playmod requested changes

2023-04-24 11:31 UTC, dead-playmod commented on packages/api-client/src/api/getProduct/fragments.ts
> +  productTaxons {
check if you can remove this

2023-04-24 11:31 UTC, dead-playmod commented on packages/api-client/src/api/getProduct/fragments.ts
> +  attributes {
check if you can remove this

2023-04-25 08:44 UTC, DawidFrankiewicz commented on packages/api-client/src/api/getProduct/fragments.ts
> +  attributes {
Can't remove this

2023-04-25 08:51 UTC, dead-playmod approved these changes

2023-05-11 17:50 UTC, merged