VSF2-146 - VSF-121 - Disabled buttons if product is out of stock, stock display, improved quantity selector logic + variant selector with changes
BitBagCommerce/SyliusVueStorefront2Frontend pull request #80
Opened 2023-04-26 07:34 UTC by DawidFrankiewicz

2023-04-27 09:01 UTC, dead-playmod requested changes

2023-04-27 13:33 UTC, DawidFrankiewicz commented on packages/theme/pages/Product.vue
> +            <div v-if="product.selectedVariant.tracked" :class="`stock-info ${productGetters.isInStock(product.selectedVariant) ? '' : 'danger'}`">
Changed according to coment

2023-04-27 13:49 UTC, DawidFrankiewicz commented on packages/theme/components/VariantSelector.vue
> +          :max="product.selectedVariant.tracked ? productGetters.getStockForVariant(product.selectedVariant) : 999"
done

2023-04-27 13:51 UTC, DawidFrankiewicz commented on packages/theme/pages/Product.vue
> +                  :max="product.selectedVariant.tracked ? productGetters.getStockForVariant(product.selectedVariant) : 999"
done

2023-04-27 13:56 UTC, DawidFrankiewicz commented on packages/composables/src/getters/productGetters.ts
> +  if (!variant.tracked) {
done

2023-04-28 14:05 UTC, dead-playmod approved these changes

2023-05-15 08:15 UTC, merged